"""create core wedding rsvp tables

Revision ID: 7d55500d4ed8
Revises: 5aa250139c54
Create Date: 2026-07-30 15:11:55.378005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d55500d4ed8'
down_revision: Union[str, Sequence[str], None] = '5aa250139c54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'VIEWER', name='admin_role', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='admin_status', native_enum=False, length=32), nullable=False),
    sa.Column('is_password_change_required', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_administrators_deleted_at'), 'administrators', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_administrators_email'), 'administrators', ['email'], unique=True)
    op.create_index(op.f('ix_administrators_role'), 'administrators', ['role'], unique=False)
    op.create_index(op.f('ix_administrators_status'), 'administrators', ['status'], unique=False)
    op.create_index(op.f('ix_administrators_username'), 'administrators', ['username'], unique=True)
    op.create_table('guests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invitation_code', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('household_name', sa.String(length=150), nullable=True),
    sa.Column('maximum_companions', sa.Integer(), nullable=False),
    sa.Column('is_primary_guest', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('INVITED', 'VERIFIED', 'BLOCKED', name='guest_status', native_enum=False, length=32), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guests_deleted_at'), 'guests', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_guests_email'), 'guests', ['email'], unique=False)
    op.create_index('ix_guests_full_name', 'guests', ['last_name', 'first_name'], unique=False)
    op.create_index(op.f('ix_guests_household_name'), 'guests', ['household_name'], unique=False)
    op.create_index(op.f('ix_guests_invitation_code'), 'guests', ['invitation_code'], unique=True)
    op.create_index(op.f('ix_guests_status'), 'guests', ['status'], unique=False)
    op.create_table('rsvps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ATTENDING', 'NOT_ATTENDING', name='rsvp_status', native_enum=False, length=32), nullable=False),
    sa.Column('attendance_type', sa.Enum('CEREMONY_AND_RECEPTION', 'CEREMONY_ONLY', 'RECEPTION_ONLY', name='attendance_type', native_enum=False, length=40), nullable=True),
    sa.Column('companion_count', sa.Integer(), nullable=False),
    sa.Column('meal_preference', sa.Enum('STANDARD', 'VEGETARIAN', 'VEGAN', 'HALAL', 'OTHER', name='meal_preference', native_enum=False, length=32), nullable=True),
    sa.Column('dietary_restrictions', sa.String(length=500), nullable=True),
    sa.Column('guest_message', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('companion_count >= 0', name='ck_rsvps_companion_count_nonnegative'),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rsvps_guest_id'), 'rsvps', ['guest_id'], unique=True)
    op.create_index(op.f('ix_rsvps_status'), 'rsvps', ['status'], unique=False)
    op.create_table('companions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rsvp_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('meal_preference', sa.Enum('STANDARD', 'VEGETARIAN', 'VEGAN', 'HALAL', 'OTHER', name='companion_meal_preference', native_enum=False, length=32), nullable=True),
    sa.Column('dietary_restrictions', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rsvp_id'], ['rsvps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companions_rsvp_id'), 'companions', ['rsvp_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companions_rsvp_id'), table_name='companions')
    op.drop_table('companions')
    op.drop_index(op.f('ix_rsvps_status'), table_name='rsvps')
    op.drop_index(op.f('ix_rsvps_guest_id'), table_name='rsvps')
    op.drop_table('rsvps')
    op.drop_index(op.f('ix_guests_status'), table_name='guests')
    op.drop_index(op.f('ix_guests_invitation_code'), table_name='guests')
    op.drop_index(op.f('ix_guests_household_name'), table_name='guests')
    op.drop_index('ix_guests_full_name', table_name='guests')
    op.drop_index(op.f('ix_guests_email'), table_name='guests')
    op.drop_index(op.f('ix_guests_deleted_at'), table_name='guests')
    op.drop_table('guests')
    op.drop_index(op.f('ix_administrators_username'), table_name='administrators')
    op.drop_index(op.f('ix_administrators_status'), table_name='administrators')
    op.drop_index(op.f('ix_administrators_role'), table_name='administrators')
    op.drop_index(op.f('ix_administrators_email'), table_name='administrators')
    op.drop_index(op.f('ix_administrators_deleted_at'), table_name='administrators')
    op.drop_table('administrators')
    # ### end Alembic commands ###
